Feature/ba-0010
khasang/businessassistant pull request #26
Opened 2018-10-24 22:29 UTC by IMozgg

added feature:
- new entity POI;
- new interface DAO for POI;
- new interface Service and Controller for POI.
fix:
- format LocalDate for column startWork;
- deny input negative value for column workTime.

2018-11-03 17:35 UTC, IMozgg commented
resolve all conflicts and change entity Poi to PointOfInterest

2018-11-04 16:45 UTC, SKuznet requested changes

2018-11-04 16:45 UTC, SKuznet commented on rest/src/main/java/io/khasang/ba/controller/PointOfInterestController.java
> +public class PoiController {
change name to full

2018-11-04 16:45 UTC, SKuznet commented on rest/src/main/java/io/khasang/ba/entity/PointOfInterest.java
> +public class Poi {
change to full

2018-11-04 16:45 UTC, SKuznet commented on rest/src/main/java/io/khasang/ba/entity/PointOfInterest.java
> +    @ColumnDefault(value = "'безымянный'")
change ru to en

2018-11-04 16:45 UTC, SKuznet commented on rest/src/main/java/io/khasang/ba/service/PointOfInterestService.java
> +public interface PoiService {
change to full  name

2018-11-04 16:45 UTC, SKuznet commented on rest/src/main/java/io/khasang/ba/service/impl/PointOfInterestServiceImpl.java
> +        poiDao.add(poi);
simplify

2018-11-04 16:45 UTC, SKuznet commented on rest/src/main/java/io/khasang/ba/service/impl/PointOfInterestServiceImpl.java
> +        Poi temp = poiDao.getById(id);
simplify

2018-11-25 18:29 UTC, merged